### ISSUE TITLE
Display bug - Robin Nano V.1.2 Sapphire Plus

### ISSUE THREAD

**Issue by pforrmi** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#12]
Hi there,

I got a bug when trying to compile my own. As you see on the picture there some display issue but I defined the correct display. With your precompiled firmware for my sapphire plus (v.1.2) it worked fine with the display.

Maybe you can give me a quick hint?!

Bests

[Archiv.zip](https://github.com/RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI/files/7183453/Archiv.zip)

![IMG_6642](https://user-images.githubusercontent.com/15838540/133740149-8e23520a-266e-44aa-b986-7e336561c944.jpg)

**Comment by RolfZuckowskiUltras** [comment]
Hey. Hmm... Thats a Issue, that never occured to me. It's a little wird, since were basically using the same Display. I would advise just to try out to compile the original MKS-Repo or an older Version of my Repo to see, if the error is consistent to you.

I mean I've seen a section in configuration_adv.h, where you can screw a little around on the borders of the Display, which should not be the case. You can also try to deactivate the LVGL-Gui for the normal Marlin Touch-GUI (see #define TFT_COLOR_UI and #define TFT_LVGL_UI)
