### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by TimCarrDP** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#13]
No matter what I change, I keep getting a black screen. Not sure why. Its working with the precompiles

**Comment by rubinator9000** [comment]
Had the same issue, fixed it by disabling LVGL_UI in configuration.h

**Comment by RolfZuckowskiUltras** [comment]
Hey this might be an Issue by MKS.[ This has been an issue before](https://github.com/RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI/issues/4). It seems to be the case, that the MKS-GUI does colide with the motion new option.
So the fix seems to be using the LVGL-GUI with classic jerk (worse printing) or the Factory-Marlin (touch) gui with new motion.

I'm a little annoyed by those compatebility-issues with LVGL, so I do plan to eventually move the full repo onto a direct marlin fork. My personal experience on it has been a lot better (see my playground-fork). I'm not quite shure, when I'm able to do that.

**Comment by CentaXx** [comment]
I also had this issue. The printer didn't boot properly, couldn't reach it via USB as well. Found the solution for me which might have caused this for you: 

When TFT_LVGL_UI is selected, in the next if clause the MKS_WIFI_MODULE is defined automatically. When outcommenting the define for MKS_WIFI_MODULE, my printer booted fine. I would suggest disabling this by default. Is there a reason why this is automatically defined if TFT_LVGL_UI is enabled?

**Comment by RolfZuckowskiUltras** [comment]
> Is there a reason why this is automatically defined if TFT_LVGL_UI is enabled?

MKS does sell a ESP32-Based Wifi-Module, which pretty mutch runs custom firmware out of the box and firmware can directly be loaded onto it, just like the Mainboard of your printer. MKS_Wifi is enabled by default from MKS. It normally just allocate the second serial port and does nothing, if not used. There is also a menu to configure the Board in the LVGL-Gui. I didn't like the MKS-Wifi features, but you can use the configuration with ESP3D on the WIFI-board, which is quite nice. Since I did not face those issues, I did not modify that feature.

**Comment by RolfZuckowskiUltras** [comment]
Should be fixed in my new follow-up-repo.
