### ISSUE TITLE
Z Speeds

### ISSUE THREAD

**Issue by mjbmz** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#19]
Hi,

for me the default Z-Speeds & Homing-Speeds where much to high. Homing/printing was impossible. I had to change these Values:

From:
`#define HOMING_FEEDRATE_MM_M { (50*60),(50*60),(40*60)}`
`#define DEFAULT_MAX_FEEDRATE          { 300, 300, 40, 50 }`

To:
`#define HOMING_FEEDRATE_MM_M { (20*60),(20*60),(4*60)}`
`#define DEFAULT_MAX_FEEDRATE          { 300, 300, 8, 50 }`

Thanks for your work

**Comment by RolfZuckowskiUltras** [comment]
Hey,
thx for the issue. I'm going to lower the homing speed, the next time I do touch the code. How fast your Z-Axis can actually go, depends a lot on lubrication, since the spindles are quite loose and sometimes tend vibrate, casusing those to block. A lower feedrate works more reliable, so thats a better decision.

**Comment by RolfZuckowskiUltras** [comment]
Fixed in my new Repo.
