### ISSUE TITLE
Can't see the thumbnail of gcode , while searching it and printing it -Sapphire pro-

### ISSUE THREAD

**Issue by Filippo-est** [RolfZuckowskiUltras/TwoTrees-Sapphire-Pro-Plus-Marlin2.0-with-GUI#8]
So , I downloaded the version for the sapphire pro , and it works well , except I can't see the gcode preview .
Before you ask , the image is inserted in gcode using pruslaslicer , is there something that can be done?

**Comment by RolfZuckowskiUltras** [comment]
Hey Filippo-est,
im not really into the usage of the prusaslicer, since i do like cura better. As far as I know, the feature is only [supported by Cura yet. You have to download a additional add-on from MKS](https://marketplace.ultimaker.com/app/cura/plugins/Jeredian/MKSWifiPlugin) to make it work. The Export with Image did only work for me by using the "save to"-Dialog in cura. The direct saving to a SD-card did not work for me.
